project 'Buckets - Basketball Info & Stats.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Buckets - Basketball Info & Stats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buckets - Basketball Info & Stats
    pod 'SwiftyJSON', '~> 4.0'
end
